### ISSUE TITLE
버그 인거 같습니다

### ISSUE THREAD

**Issue by ghost** [monun/kotlin-plugin#2]
https://github.com/monun/kotlin-plugin/releases  에 있는

1.0.8

Kotlin-1.5.10.jar 을 

(마인크래프트) 서버에 플러그인으로 적용 시켰지만 

/pl 쳐보아도 적용이 안됩니다

**Comment by monun** [comment]
JDK 8로 컴파일한 1.1.0 버전을 올려두었습니다
테스트해보세요

**Comment by ghost** [comment]
아하 넵!

**Comment by papakia1234** [comment]
와 감사합니다
작동 잘합니다 감사합니다 각★별 님
